import './style.css';

const projects = [
  { id: 1, name: 'ABC Apartment Water Leakage', client: 'ABC Apartments', type: 'Water leakage', contract: 1200000, budget: 800000, spent: 420000, received: 500000, status: 'Active', color: 'teal' },
  { id: 2, name: 'XYZ Residential AMC', client: 'XYZ Properties', type: 'AMC', contract: 800000, budget: 480000, spent: 210000, received: 225000, status: 'Active', color: 'violet' },
  { id: 3, name: 'DEF Commercial Plumbing', client: 'DEF Industries', type: 'Plumbing', contract: 1500000, budget: 950000, spent: 650000, received: 700000, status: 'At risk', color: 'orange' },
  { id: 4, name: 'GHI Electrical Maintenance', client: 'GHI Logistics', type: 'Electrical', contract: 1000000, budget: 600000, spent: 380000, received: 400000, status: 'Active', color: 'blue' },
  { id: 5, name: 'JKL Emergency Pipe Repair', client: 'JKL Residency', type: 'Emergency', contract: 450000, budget: 300000, spent: 132000, received: 150000, status: 'Active', color: 'pink' },
];

let expenses = [
  { date: '18 Sep 2026', description: 'Waterproofing compound', category: 'Materials', project: 'ABC Apartment Water Leakage', vendor: 'ABC Hardware', amount: 18500, method: 'UPI' },
  { date: '17 Sep 2026', description: 'Weekly labour payout', category: 'Labour', project: 'DEF Commercial Plumbing', vendor: 'Ramesh & team', amount: 12000, method: 'Bank transfer' },
  { date: '16 Sep 2026', description: 'Delivery and loading', category: 'Transport', project: 'XYZ Residential AMC', vendor: 'City Logistics', amount: 4500, method: 'Cash' },
  { date: '15 Sep 2026', description: 'PVC pipes and fittings', category: 'Materials', project: 'ABC Apartment Water Leakage', vendor: 'DEF Pipes', amount: 25000, method: 'UPI' },
];

const rupee = (n) => `₹${new Intl.NumberFormat('en-IN').format(n)}`;
const compact = (n) => n >= 100000 ? `₹${(n / 100000).toFixed(1)}L` : rupee(n);
const total = (key) => projects.reduce((sum, p) => sum + p[key], 0);

function icon(name) {
  const icons = { grid: '▦', folder: '▣', wallet: '◉', users: '♙', box: '▤', calendar: '◫', file: '▤', chart: '⌁', settings: '⚙', bell: '♧', search: '⌕', plus: '+', arrow: '↗', more: '•••', receipt: '▥', chevron: '⌄' };
  return `<span class="icon">${icons[name] || '·'}</span>`;
}

function appShell(content, active = 'Dashboard') {
  const nav = [
    ['Dashboard', 'grid'], ['Projects', 'folder'], ['Finance', 'wallet'], ['Vendors', 'users'], ['Labour', 'users'], ['Materials', 'box'], ['AMC contracts', 'calendar'], ['Documents', 'file'], ['Reports', 'chart']
  ];
  return `<div class="app-shell">
    <aside class="sidebar"><div class="brand"><div class="brand-mark">C</div><div><strong>contractflow</strong><small>Finance & operations</small></div></div>
      <div class="workspace-label">WORKSPACE</div><nav>${nav.map(([label, ico]) => label === 'Finance' ? `<div class="nav-group"><button class="nav-item ${active === label || ['Expenses','Receivables','Payables','Cash Flow'].includes(active) ? 'active' : ''}" data-finance-toggle>${icon(ico)}<span>${label}</span><span class="nav-caret">${icon('chevron')}</span></button><div class="finance-subnav ${['Expenses','Receivables','Payables','Cash Flow'].includes(active) ? 'open' : ''}"><button data-nav="Expenses">Expenses</button><button data-nav="Receivables">Receivables</button><button data-nav="Payables">Payables</button><button data-nav="Cash Flow">Cash flow</button></div></div>` : `<button class="nav-item ${active === label ? 'active' : ''}" data-nav="${label}">${icon(ico)}<span>${label}</span></button>`).join('')}</nav>
      <div class="sidebar-bottom"><button class="nav-item" data-nav="Company settings">${icon('settings')}<span>Settings</span></button><div class="help-card" data-nav="Help center"><span class="help-icon">?</span><div><strong>Need a hand?</strong><small>Visit help centre</small></div>${icon('arrow')}</div><div class="profile"><div class="avatar">AK</div><div><strong>Arjun Kumar</strong><small>Owner account</small></div><span>⌄</span></div></div>
    </aside>
    <main class="main"><header class="topbar"><button class="mobile-menu">☰</button><div class="breadcrumb">Workspace <span>/</span> <b>${active}</b></div><div class="top-actions"><div class="global-search search-wrap">${icon('search')}<input id="global-search" placeholder="Search anything..." autocomplete="off" /><kbd>⌘ K</kbd><div class="search-results" id="search-results"></div></div><div class="theme-toggle" role="group" aria-label="Color theme"><button class="theme-option" data-theme-choice="light">☼ Light</button><button class="theme-option" data-theme-choice="dark">◐ Dark</button></div><div class="dropdown-wrap"><button class="icon-button" id="notifications-button" aria-label="Notifications">${icon('bell')}<i></i></button><div class="popover notifications-popover" id="notifications-popover"><strong>Notifications</strong><div class="notification-item"><span class="notice-dot danger-dot"></span><div><b>Payment overdue</b><small>ABC Apartments · ₹2,00,000</small></div></div><div class="notification-item"><span class="notice-dot warning-dot"></span><div><b>Budget warning</b><small>DEF Plumbing is at 68%</small></div></div><button class="popover-link">View all notifications</button></div></div><button class="icon-button" id="help-button" aria-label="Help center">?</button><div class="dropdown-wrap"><button class="profile-trigger" id="profile-button" aria-label="Open profile"><span class="mini-avatar">AK</span><span class="profile-chevron">⌄</span></button><div class="popover profile-popover" id="profile-popover"><div class="profile-popover-head"><span class="mini-avatar">AK</span><div><b>Arjun Kumar</b><small>Owner account</small></div></div><button class="menu-link" data-nav="Profile settings">Profile settings</button><button class="menu-link" data-nav="Company settings">Company settings</button><button class="menu-link">Sign out</button></div></div></div></header>${content}</main>
  </div>`;
}

function dashboard() {
  return appShell(`<section class="page"><div class="page-heading"><div><div class="eyebrow">THURSDAY, 18 SEPTEMBER 2026</div><h1>${timeGreeting()}, Arjun <span class="wave">✦</span></h1><p>Here’s what’s happening across your projects today.</p></div><button class="button primary" id="new-expense">${icon('plus')} Add expense</button></div>
    <div class="kpi-grid">${[
      ['Active projects', '06', '+2 this month', 'up', 'folder'], ['Contract value', '₹52.4L', 'Across 6 projects', 'neutral', 'receipt'], ['Project expenses', '₹18.7L', '+12.4% vs last month', 'down', 'wallet'], ['Payments received', '₹14.8L', '28.2% of contract value', 'up', 'arrow'], ['Receivables', '₹37.6L', '₹2.4L overdue', 'alert', 'calendar'], ['Money invested', '₹3.9L', 'Across 5 projects', 'neutral', 'chart']
    ].map(([label, value, note, tone, ico]) => `<div class="kpi-card"><div class="kpi-top"><span>${label}</span><span class="metric-icon ${tone}">${icon(ico)}</span></div><strong>${value}</strong><small class="${tone}">${tone === 'up' ? '↗ ' : tone === 'down' ? '↗ ' : ''}${note}</small></div>`).join('')}</div>
    <div class="content-grid"><div class="panel project-panel"><div class="panel-heading"><div><h2>Project financial overview</h2><p>Track budget utilisation across active projects</p></div><button class="text-button">View all ${icon('arrow')}</button></div><div class="table-wrap"><table><thead><tr><th>Project</th><th>Contract value</th><th>Spent</th><th>Remaining</th><th>Progress</th><th>Status</th></tr></thead><tbody>${projects.slice(0, 4).map(p => `<tr class="project-row" data-project="${p.id}"><td><div class="project-name"><span class="project-dot ${p.color}"></span><div><strong>${p.name}</strong><small>${p.client}</small></div></div></td><td>${compact(p.contract)}</td><td>${compact(p.spent)}</td><td>${compact(p.budget - p.spent)}</td><td><div class="progress-line"><span><i style="width:${Math.round(p.spent / p.budget * 100)}%"></i></span><small>${Math.round(p.spent / p.budget * 100)}%</small></div></td><td><span class="status ${p.status === 'At risk' ? 'warning' : 'success'}">${p.status}</span></td></tr>`).join('')}</tbody></table></div></div>
      <div class="panel invest-panel"><div class="panel-heading"><div><h2>Money invested</h2><p>Your cash tied up in projects</p></div><button class="more-button">•••</button></div><div class="invest-total"><strong>₹3,90,000</strong><span class="status neutral">5 projects</span></div><div class="investment-list">${projects.slice(0, 4).map(p => `<div class="investment-item"><div><strong>${p.name.split(' ').slice(0, 2).join(' ')}</strong><small>${p.client}</small></div><b>${compact(Math.max(p.spent - p.received, 0))}</b></div>`).join('')}</div><button class="button secondary full" id="investment-report">View investment report ${icon('arrow')}</button></div>
    </div><div class="content-grid lower-grid"><div class="panel chart-panel"><div class="panel-heading"><div><h2>Cash flow</h2><p>Income vs expenses · Last 6 months</p></div><button class="select-button">Last 6 months ${icon('chevron')}</button></div><div class="legend"><span><i class="legend-dot income"></i> Client income</span><span><i class="legend-dot expense"></i> Project expenses</span></div><div class="bar-chart">${[['Apr','60','35'],['May','78','47'],['Jun','55','38'],['Jul','88','54'],['Aug','72','61'],['Sep','94','48']].map(([m, a, b]) => `<div class="bar-group"><div class="bars"><i class="income-bar" style="height:${a}%"></i><i class="expense-bar" style="height:${b}%"></i></div><small>${m}</small></div>`).join('')}</div></div><div class="panel transactions-panel"><div class="panel-heading"><div><h2>Recent transactions</h2><p>Latest activity across your workspace</p></div><button class="text-button">See all ${icon('arrow')}</button></div><div class="transactions">${[['Client payment received','ABC Apartments','+ ₹2,00,000','today','income'],['Waterproofing compound','ABC Hardware','- ₹18,500','today','expense'],['Weekly labour payout','Ramesh & team','- ₹12,000','yesterday','expense'],['Client payment received','XYZ Properties','+ ₹75,000','16 Sep','income']].map(([a,b,c,d,t]) => `<div class="transaction"><span class="transaction-icon ${t}">${t === 'income' ? '↗' : '↘'}</span><div><strong>${a}</strong><small>${b} · ${d}</small></div><b class="${t}">${c}</b></div>`).join('')}</div></div></div>
  </section>`, 'Dashboard');
}

function projectsPage() {
  return appShell(`<section class="page"><div class="page-heading"><div><div class="eyebrow">WORKSPACE</div><h1>Projects</h1><p>Manage project finances, budgets and profitability.</p></div><button class="button primary">${icon('plus')} New project</button></div><div class="tabs"><button class="tab active">All projects <span>10</span></button><button class="tab">Active <span>6</span></button><button class="tab">Completed <span>3</span></button><button class="tab">At risk <span>1</span></button></div><div class="panel table-panel"><div class="table-toolbar"><div class="table-search">${icon('search')}<input placeholder="Search projects..." /></div><button class="filter-button">Filter ${icon('chevron')}</button><button class="filter-button">Export ${icon('arrow')}</button></div><div class="table-wrap"><table><thead><tr><th>Project</th><th>Type</th><th>Contract value</th><th>Spent</th><th>Received</th><th>Profit</th><th>Status</th><th></th></tr></thead><tbody>${projects.map(p => `<tr><td><div class="project-name"><span class="project-dot ${p.color}"></span><div><strong>${p.name}</strong><small>${p.client}</small></div></div></td><td>${p.type}</td><td>${compact(p.contract)}</td><td>${compact(p.spent)}</td><td>${compact(p.received)}</td><td class="income">${compact(p.contract - p.spent)}</td><td><span class="status ${p.status === 'At risk' ? 'warning' : 'success'}">${p.status}</span></td><td><button class="more-button">•••</button></td></tr>`).join('')}</tbody></table></div></div></section>`, 'Projects');
}

function financePage(title = 'Expenses') {
  const isReceivable = title === 'Receivables';
  return appShell(`<section class="page"><div class="page-heading"><div><div class="eyebrow">FINANCE / ${title.toUpperCase()}</div><h1>${title}</h1><p>${isReceivable ? 'Keep track of money due from your clients.' : 'Every rupee, connected to the work it belongs to.'}</p></div><button class="button primary" id="new-expense">${icon('plus')} ${isReceivable ? 'Record payment' : 'Add expense'}</button></div><div class="mini-kpis"><div><small>${isReceivable ? 'Total receivables' : 'This month'}</small><strong>${isReceivable ? '₹37.6L' : '₹2,84,500'}</strong><span class="income">↗ 8.4%</span></div><div><small>${isReceivable ? 'Overdue amount' : 'Pending bills'}</small><strong>${isReceivable ? '₹2.4L' : '₹1,35,000'}</strong><span class="alert">Needs attention</span></div><div><small>${isReceivable ? 'Due this week' : 'Transactions'}</small><strong>${isReceivable ? '₹4.8L' : '48'}</strong><span class="muted">Across all projects</span></div></div><div class="panel table-panel"><div class="table-toolbar"><div class="table-search">${icon('search')}<input placeholder="Search ${title.toLowerCase()}..." /></div><button class="filter-button">All projects ${icon('chevron')}</button><button class="filter-button">Date range ${icon('chevron')}</button></div><div class="table-wrap"><table><thead><tr>${(isReceivable ? ['Client','Project','Invoice','Amount','Due date','Status',''] : ['Date','Description','Category','Project','Vendor','Amount','Method','']).map(h => `<th>${h}</th>`).join('')}</tr></thead><tbody>${isReceivable ? [['ABC Apartments','Water Leakage repair','INV-0042','₹2,00,000','25 Sep','Due soon'],['DEF Industries','Commercial plumbing','INV-0039','₹1,50,000','05 Oct','Pending'],['XYZ Properties','Residential AMC','INV-0036','₹75,000','15 Sep','Overdue'],['GHI Logistics','Electrical maintenance','INV-0035','₹1,20,000','28 Sep','Due soon']].map(r => `<tr>${r.map((x,i) => `<td>${i === 5 ? `<span class="status ${x === 'Overdue' ? 'danger' : x === 'Due soon' ? 'warning' : 'neutral'}">${x}</span>` : i === 3 ? `<strong>${x}</strong>` : x}</td>`).join('')}<td><button class="more-button">•••</button></td></tr>`).join('') : expenses.map(e => `<tr><td>${e.date}</td><td><strong>${e.description}</strong></td><td><span class="category">${e.category}</span></td><td>${e.project}</td><td>${e.vendor}</td><td><strong>${rupee(e.amount)}</strong></td><td>${e.method}</td><td><button class="more-button">•••</button></td></tr>`).join('')}</tbody></table></div></div></section>`, title); }

function modal() { return `<div class="modal-backdrop" id="modal"><div class="modal"><div class="modal-head"><div><div class="eyebrow">QUICK ENTRY</div><h2>Add expense</h2><p>Record a project cost in a few seconds.</p></div><button class="close-modal">×</button></div><form id="expense-form"><label>Project<select required><option>ABC Apartment Water Leakage</option><option>XYZ Residential AMC</option><option>DEF Commercial Plumbing</option></select></label><div class="form-row"><label>Category<select><option>Materials</option><option>Labour</option><option>Transport</option><option>Equipment</option><option>Site expenses</option></select></label><label>Amount<input required type="number" placeholder="₹ 0" /></label></div><div class="form-row"><label>Vendor<input placeholder="Search or add vendor" /></label><label>Payment method<select><option>UPI</option><option>Cash</option><option>Bank transfer</option><option>Card</option></select></label></div><label>Description <input placeholder="What was this expense for?" /></label><label class="check-label"><input type="checkbox" /> Paid with personal money <small>Counts towards money invested</small></label><div class="modal-actions"><button type="button" class="button secondary close-modal">Cancel</button><button class="button primary" type="submit">Save expense ${icon('arrow')}</button></div></form></div></div>`; }

function settingsPage(kind) {
  const profile = kind === 'Profile settings';
  return appShell(`<section class="page settings-page"><div class="page-heading"><div><div class="eyebrow">SETTINGS / ${profile ? 'PROFILE' : 'COMPANY'}</div><h1>${profile ? 'Profile settings' : 'Company settings'}</h1><p>${profile ? 'Manage your personal details and account security.' : 'Keep your company information accurate across reports and documents.'}</p></div><button class="button primary save-settings">Save changes</button></div><div class="settings-layout"><div class="settings-nav"><button class="settings-nav-item ${profile ? 'active' : ''}" data-nav="Profile settings">Personal information</button><button class="settings-nav-item ${!profile ? 'active' : ''}" data-nav="Company settings">Company profile</button><button class="settings-nav-item">Notifications</button><button class="settings-nav-item">Security</button></div><div class="panel settings-card"><div class="settings-section"><h2>${profile ? 'Personal information' : 'Company profile'}</h2><p>${profile ? 'This information is used to identify you in your workspace.' : 'This information appears on your invoices and financial reports.'}</p><div class="avatar-upload"><div class="large-avatar">${profile ? 'AK' : 'CF'}</div><div><button class="button secondary">Change photo</button><small>JPG or PNG. Max 2MB.</small></div></div><div class="form-grid"><label>${profile ? 'Full name' : 'Company name'}<input value="${profile ? 'Arjun Kumar' : 'Kumar Contractor Services'}" /></label><label>${profile ? 'Email address' : 'GSTIN'}<input value="${profile ? 'arjun@kumarcontractor.in' : '33ABCDE1234F1Z5'}" /></label><label>${profile ? 'Phone number' : 'Company phone'}<input value="${profile ? '+91 98765 43210' : '+91 98765 43210'}" /></label><label>${profile ? 'Role' : 'Financial year'}<input value="${profile ? 'Owner' : 'April - March'}" /></label></div></div>${profile ? `<div class="settings-section"><h2>Security</h2><p>Update your password regularly to keep your account secure.</p><button class="button secondary">Change password</button></div>` : `<div class="settings-section"><h2>Business address</h2><p>Used for invoices, contracts and company documents.</p><label>Address<textarea>12 Mount Road, Chennai, Tamil Nadu 600002</textarea></label><div class="form-grid"><label>Currency<select><option>Indian Rupee (₹)</option></select></label><label>Default payment terms<select><option>Net 30 days</option><option>Net 15 days</option></select></label></div></div>`}</div></div></section>`, kind); }

function helpPage() { return appShell(`<section class="page help-page"><div class="page-heading"><div><div class="eyebrow">SUPPORT</div><h1>How can we help?</h1><p>Find quick answers for using ContractFlow Finance.</p></div></div><div class="help-grid"><div class="panel help-feature"><span class="help-feature-icon">?</span><h2>Start with the basics</h2><p>Learn how to create a project, add an expense, and understand money invested.</p><button class="button primary">Open quick-start guide ${icon('arrow')}</button></div><div class="panel help-feature"><span class="help-feature-icon">⌕</span><h2>Search help articles</h2><p>Find answers about payments, budgets, vendors, and reports.</p><div class="table-search">${icon('search')}<input placeholder="Search help articles..." /></div></div><div class="panel help-feature"><span class="help-feature-icon">↗</span><h2>Contact support</h2><p>Need more help? Our support team is ready to assist.</p><button class="button secondary">Contact support</button></div></div></section>`, 'Help center'); }

function investmentReportPage() { const invested = projects.map(project => ({ ...project, invested: Math.max(project.spent - project.received, 0) })); const totalInvested = invested.reduce((sum, project) => sum + project.invested, 0); return appShell(`<section class="page"><div class="page-heading"><div><div class="eyebrow">REPORTS / CASH POSITION</div><h1>Investment report</h1><p>See how much of your own money is currently tied up in each project.</p></div><button class="button primary" id="export-report">Export report ${icon('arrow')}</button></div><div class="mini-kpis"><div><small>Total invested</small><strong>${compact(totalInvested)}</strong><span class="muted">Across active projects</span></div><div><small>Projects funded</small><strong>${invested.filter(project => project.invested > 0).length}</strong><span class="muted">With expenses above receipts</span></div><div><small>Highest investment</small><strong>${compact(Math.max(...invested.map(project => project.invested)))}</strong><span class="alert">Review cash position</span></div></div><div class="panel table-panel investment-report"><div class="panel-heading"><div><h2>Investment by project</h2><p>Project expenses minus client payments received</p></div></div><div class="table-wrap"><table><thead><tr><th>Project</th><th>Project expenses</th><th>Payments received</th><th>Your money invested</th><th>Share of total</th></tr></thead><tbody>${invested.map(project => `<tr><td><div class="project-name"><span class="project-dot ${project.color}"></span><div><strong>${project.name}</strong><small>${project.client}</small></div></div></td><td>${compact(project.spent)}</td><td>${compact(project.received)}</td><td><strong class="income">${compact(project.invested)}</strong></td><td><div class="progress-line"><span><i style="width:${totalInvested ? Math.round(project.invested / totalInvested * 100) : 0}%"></i></span><small>${totalInvested ? Math.round(project.invested / totalInvested * 100) : 0}%</small></div></td></tr>`).join('')}</tbody></table></div></div></section>`, 'Investment report'); }

function render(page = 'dashboard') { document.querySelector('#modal')?.remove(); document.querySelector('#app').innerHTML = page === 'dashboard' ? dashboard() : page === 'projects' ? projectsPage() : page === 'investment-report' ? investmentReportPage() : page === 'Profile settings' || page === 'Company settings' ? settingsPage(page) : page === 'Help center' ? helpPage() : financePage(page); document.body.insertAdjacentHTML('beforeend', modal()); bind(); }

function bind() {
  setTheme(document.body.dataset.theme || 'light');
  document.querySelectorAll('[data-nav]').forEach(b => b.addEventListener('click', () => { const n = b.dataset.nav; render(n === 'Dashboard' ? 'dashboard' : n === 'Projects' ? 'projects' : n === 'Finance' ? 'Expenses' : n === 'Reports' ? 'Reports' : n); }));
  document.querySelector('[data-finance-toggle]')?.addEventListener('click', () => { document.querySelector('.finance-subnav')?.classList.toggle('open'); document.querySelector('[data-finance-toggle]')?.classList.toggle('expanded'); });
  document.querySelectorAll('#new-expense').forEach(b => b.addEventListener('click', () => document.querySelector('#modal').classList.add('open')));
  document.querySelector('#investment-report')?.addEventListener('click', () => render('investment-report'));
  document.querySelector('#export-report')?.addEventListener('click', () => toast('Investment report export is ready'));
  document.querySelectorAll('.close-modal').forEach(b => b.addEventListener('click', () => document.querySelector('#modal').remove()));
  document.querySelector('#expense-form')?.addEventListener('submit', e => { e.preventDefault(); document.querySelector('#modal').remove(); toast('Expense added successfully'); });
  document.querySelectorAll('.project-row').forEach(row => row.addEventListener('click', () => toast('Project details are ready for the next workflow')));
  document.querySelector('.mobile-menu')?.addEventListener('click', () => document.querySelector('.sidebar').classList.toggle('mobile-open'));
  document.querySelectorAll('[data-theme-choice]').forEach(button => button.addEventListener('click', () => setTheme(button.dataset.themeChoice)));
  document.querySelector('#notifications-button')?.addEventListener('click', event => { event.stopPropagation(); closePopovers('notifications-popover'); document.querySelector('#notifications-popover').classList.toggle('open'); });
  document.querySelector('#profile-button')?.addEventListener('click', event => { event.stopPropagation(); closePopovers('profile-popover'); document.querySelector('#profile-popover').classList.toggle('open'); });
  document.querySelector('#help-button')?.addEventListener('click', event => { event.stopPropagation(); render('Help center'); });
  document.querySelector('#global-search')?.addEventListener('input', event => showSearchResults(event.target.value));
  document.querySelector('#global-search')?.addEventListener('focus', event => showSearchResults(event.target.value));
  document.querySelectorAll('.popover').forEach(popover => popover.addEventListener('click', event => event.stopPropagation()));
  document.addEventListener('click', event => { if (!event.target.closest('.search-wrap, .dropdown-wrap')) closePopovers(); });
  document.querySelectorAll('.save-settings').forEach(button => button.addEventListener('click', () => toast('Settings saved successfully')));
}
function toast(message) { const t = document.createElement('div'); t.className = 'toast'; t.innerHTML = `<span>✓</span>${message}`; document.body.appendChild(t); setTimeout(() => t.remove(), 2800); }

const searchItems = [
  ...projects.map(project => ({ type: 'Project', title: project.name, detail: project.client, page: 'projects' })),
  ...expenses.map(expense => ({ type: 'Expense', title: expense.description, detail: `${expense.vendor} · ${rupee(expense.amount)}`, page: 'Expenses' })),
  { type: 'Vendor', title: 'ABC Hardware', detail: 'Materials supplier · ₹75,000 outstanding', page: 'Vendors' },
  { type: 'Vendor', title: 'DEF Pipes', detail: 'Materials supplier · Project ABC', page: 'Vendors' },
  { type: 'Payment', title: 'ABC Apartments payment', detail: '₹2,00,000 · Received today', page: 'Expenses' },
  { type: 'Worker', title: 'Ramesh Kumar', detail: 'Plumber · ₹900/day', page: 'Labour' },
];

function showSearchResults(value) {
  const results = document.querySelector('#search-results');
  if (!results) return;
  const query = value.trim().toLowerCase();
  if (!query) { results.classList.remove('open'); results.innerHTML = ''; return; }
  const matches = searchItems.filter(item => `${item.title} ${item.detail} ${item.type}`.toLowerCase().includes(query)).slice(0, 6);
  results.innerHTML = matches.length ? matches.map(item => `<button class="search-result" data-result-page="${item.page}"><span class="result-type">${item.type}</span><span><b>${item.title}</b><small>${item.detail}</small></span><span class="result-arrow">↗</span></button>`).join('') : '<div class="no-results">No projects, vendors, or transactions found.</div>';
  results.classList.add('open');
  results.querySelectorAll('[data-result-page]').forEach(result => result.addEventListener('click', () => { results.classList.remove('open'); render(result.dataset.resultPage === 'projects' ? 'projects' : result.dataset.resultPage); }));
}

function closePopovers(except) {
  document.querySelectorAll('.popover.open').forEach(popover => { if (popover.id !== except) popover.classList.remove('open'); });
  document.querySelector('#search-results')?.classList.remove('open');
}

function setTheme(theme) {
  document.body.dataset.theme = theme;
  localStorage.setItem('contractflow-theme', theme);
  document.querySelectorAll('[data-theme-choice]').forEach(button => button.classList.toggle('selected', button.dataset.themeChoice === theme));
}

function timeGreeting() {
  const hour = new Date().getHours();
  if (hour < 5) return 'Good night';
  if (hour < 12) return 'Good morning';
  if (hour < 17) return 'Good afternoon';
  if (hour < 21) return 'Good evening';
  return 'Good night';
}

setTheme(localStorage.getItem('contractflow-theme') || 'light');
render();
